apiVersion: v1
kind: Service
metadata:
  name: mariadb-node1
spec:
  selector:
    app: mariadb-node1
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: sst
    port: 4444
    protocol: TCP
    targetPort: 4444
  - name: replication-udp
    port: 4567
    protocol: UDP
    targetPort: 4567
  - name: replication
    port: 4567
    protocol: TCP
    targetPort: 4567
  - name: ist
    port: 4568
    protocol: TCP
    targetPort: 4568
